# ---- Development profile ----
spring:
  jpa:
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    com.maram.payroll: DEBUG
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG

management:
  endpoint:
    health:
      show-details: always
